services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: war-analysis

    working_dir: /app

    volumes:
      - .:/app

    command: python scripts/read_ods.py