services:
  app:
    user: "${UID}:${GID}"

    build:
      context: .
      dockerfile: Dockerfile

    container_name: war-analysis

    working_dir: /app

    environment:
      PYTHONPATH: /app
      HOME: /tmp
      MPLCONFIGDIR: /tmp/matplotlib
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

    volumes:
      - .:/app
  
    depends_on:
      postgres:
        condition: service_healthy 

    command: tail -f /dev/null
  postgres:
    # image: postgis/postgis:17-3.5
    image: postgis/postgis@sha256:01a6a70e41e6c4467c8f55f6063555ed72db2d6662cd0d571040d42eadaeb6f6
    restart: unless-stopped
    healthcheck:                                 # new block
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # ports:
      # - "${POSTGRES_PORT}:5432"

    volumes:
      - ./data/db/postgres:/var/lib/postgresql/data