services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: war-analysis

    working_dir: /app

    environment:
      PYTHONPATH: /app  
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

    volumes:
      - .:/app
  
    depends_on:
      - postgres

    command: tail -f /dev/null
  postgres:
    image: postgres:17
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - ./data/db/postgres:/var/lib/postgresql/data