"""add timestamps

Revision ID: 3810b76c360f
Revises: 8300c2552723
Create Date: 2026-09-10 09:28:29.583488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3810b76c360f'
down_revision: Union[str, Sequence[str], None] = '8300c2552723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('locations', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('military_units', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('military_units', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('places', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('places', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('soldier_sources', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('soldier_sources', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('soldiers', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('soldiers', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('sources', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('sources', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'updated_at')
    op.drop_column('sources', 'created_at')
    op.drop_column('soldiers', 'updated_at')
    op.drop_column('soldiers', 'created_at')
    op.drop_column('soldier_sources', 'updated_at')
    op.drop_column('soldier_sources', 'created_at')
    op.drop_column('places', 'updated_at')
    op.drop_column('places', 'created_at')
    op.drop_column('military_units', 'updated_at')
    op.drop_column('military_units', 'created_at')
    op.drop_column('locations', 'updated_at')
    op.drop_column('locations', 'created_at')
    # ### end Alembic commands ###
