"""add wounded location to soldiers

Revision ID: 44ba240b7ea4
Revises: 508e3682dd81
Create Date: 2026-09-13 13:21:32.705156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44ba240b7ea4'
down_revision: Union[str, Sequence[str], None] = '508e3682dd81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('soldiers', sa.Column('wounded_location_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_soldiers_wounded_location_id'), 'soldiers', ['wounded_location_id'], unique=False)
    op.create_foreign_key(None, 'soldiers', 'locations', ['wounded_location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'soldiers', type_='foreignkey')
    op.drop_index(op.f('ix_soldiers_wounded_location_id'), table_name='soldiers')
    op.drop_column('soldiers', 'wounded_location_id')
    # ### end Alembic commands ###
