"""add deepstatemap geo data

Revision ID: 508e3682dd81
Revises: c3984649d64a
Create Date: 2026-09-12 11:19:56.108089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '508e3682dd81'
down_revision: Union[str, Sequence[str], None] = 'c3984649d64a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE EXTENSION IF NOT EXISTS postgis"
    )

    op.create_table(
        'deepstatemap_geo_data',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('snapshot_date', sa.Date(), nullable=False),
        sa.Column(
            'geometry',
            geoalchemy2.types.Geometry(
                geometry_type='MULTIPOLYGON',
                srid=4326,
                dimension=2,
                from_text='ST_GeomFromEWKT',
                name='geometry',
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'snapshot_date',
            name='uq_deepstatemap_geo_data_snapshot_date'
        )
    )

    op.create_index(
        'idx_deepstatemap_geo_data_geometry',
        'deepstatemap_geo_data',
        ['geometry'],
        unique=False,
        postgresql_using='gist'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'idx_deepstatemap_geo_data_geometry',
        table_name='deepstatemap_geo_data',
        postgresql_using='gist'
    )
    op.drop_table('deepstatemap_geo_data')
    # ### end Alembic commands ###
