"""create initial tables

Revision ID: 8300c2552723
Revises: 
Create Date: 2026-09-07 19:26:44.974977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8300c2552723'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('military_units',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'url', name='uq_military_units_name_url', postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_military_units_url'), 'military_units', ['url'], unique=False)
    op.create_table('places',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'url', name='uq_places_name_url', postgresql_nulls_not_distinct=True)
    )
    op.create_table('sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_url'), 'sources', ['url'], unique=True)
    op.create_table('locations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('settlement_id', sa.Uuid(), nullable=True),
    sa.Column('community_id', sa.Uuid(), nullable=True),
    sa.Column('district_id', sa.Uuid(), nullable=True),
    sa.Column('oblast_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['places.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['places.id'], ),
    sa.ForeignKeyConstraint(['oblast_id'], ['places.id'], ),
    sa.ForeignKeyConstraint(['settlement_id'], ['places.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('settlement_id', 'community_id', 'district_id', 'oblast_id', name='uq_locations_places', postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_locations_community_id'), 'locations', ['community_id'], unique=False)
    op.create_index(op.f('ix_locations_district_id'), 'locations', ['district_id'], unique=False)
    op.create_index(op.f('ix_locations_oblast_id'), 'locations', ['oblast_id'], unique=False)
    op.create_index(op.f('ix_locations_settlement_id'), 'locations', ['settlement_id'], unique=False)
    op.create_table('soldiers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('date_of_disappearance', sa.Date(), nullable=True),
    sa.Column('date_of_death', sa.Date(), nullable=True),
    sa.Column('date_of_burial', sa.Date(), nullable=True),
    sa.Column('date_of_release_from_captivity', sa.Date(), nullable=True),
    sa.Column('conscription', sa.String(), nullable=True),
    sa.Column('posthumous_award_date', sa.Date(), nullable=True),
    sa.Column('posthumous_award_url', sa.String(), nullable=True),
    sa.Column('cause_of_death', sa.Text(), nullable=True),
    sa.Column('rank', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('from_location_id', sa.Uuid(), nullable=True),
    sa.Column('disappeared_in_id', sa.Uuid(), nullable=True),
    sa.Column('died_in_id', sa.Uuid(), nullable=True),
    sa.Column('buried_in_id', sa.Uuid(), nullable=True),
    sa.Column('military_unit_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['buried_in_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['died_in_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['disappeared_in_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['military_unit_id'], ['military_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soldiers_buried_in_id'), 'soldiers', ['buried_in_id'], unique=False)
    op.create_index(op.f('ix_soldiers_died_in_id'), 'soldiers', ['died_in_id'], unique=False)
    op.create_index(op.f('ix_soldiers_disappeared_in_id'), 'soldiers', ['disappeared_in_id'], unique=False)
    op.create_index(op.f('ix_soldiers_from_location_id'), 'soldiers', ['from_location_id'], unique=False)
    op.create_index(op.f('ix_soldiers_military_unit_id'), 'soldiers', ['military_unit_id'], unique=False)
    op.create_table('soldier_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('soldier_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('is_primary_source', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['soldier_id'], ['soldiers.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('soldier_id', 'source_id', name='uq_soldier_sources_soldier_source')
    )
    op.create_index(op.f('ix_soldier_sources_soldier_id'), 'soldier_sources', ['soldier_id'], unique=False)
    op.create_index(op.f('ix_soldier_sources_source_id'), 'soldier_sources', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_soldier_sources_source_id'), table_name='soldier_sources')
    op.drop_index(op.f('ix_soldier_sources_soldier_id'), table_name='soldier_sources')
    op.drop_table('soldier_sources')
    op.drop_index(op.f('ix_soldiers_military_unit_id'), table_name='soldiers')
    op.drop_index(op.f('ix_soldiers_from_location_id'), table_name='soldiers')
    op.drop_index(op.f('ix_soldiers_disappeared_in_id'), table_name='soldiers')
    op.drop_index(op.f('ix_soldiers_died_in_id'), table_name='soldiers')
    op.drop_index(op.f('ix_soldiers_buried_in_id'), table_name='soldiers')
    op.drop_table('soldiers')
    op.drop_index(op.f('ix_locations_settlement_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_oblast_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_district_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_community_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_sources_url'), table_name='sources')
    op.drop_table('sources')
    op.drop_table('places')
    op.drop_index(op.f('ix_military_units_url'), table_name='military_units')
    op.drop_table('military_units')
    # ### end Alembic commands ###
