"""add date precision

Revision ID: c3984649d64a
Revises: f6213b907f7a
Create Date: 2026-09-11 09:05:31.108908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3984649d64a'
down_revision: Union[str, Sequence[str], None] = 'f6213b907f7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('soldiers', sa.Column('date_of_birth_precision', sa.Enum('DAY', 'MONTH', 'YEAR', name='date_precision'), nullable=True))
    op.add_column('soldiers', sa.Column('date_of_disappearance_precision', sa.Enum('DAY', 'MONTH', 'YEAR', name='date_precision'), nullable=True))
    op.add_column('soldiers', sa.Column('date_of_death_precision', sa.Enum('DAY', 'MONTH', 'YEAR', name='date_precision'), nullable=True))
    op.add_column('soldiers', sa.Column('date_of_burial_precision', sa.Enum('DAY', 'MONTH', 'YEAR', name='date_precision'), nullable=True))
    op.add_column('soldiers', sa.Column('date_of_release_from_captivity_precision', sa.Enum('DAY', 'MONTH', 'YEAR', name='date_precision'), nullable=True))
    op.add_column('soldiers', sa.Column('posthumous_award_date_precision', sa.Enum('DAY', 'MONTH', 'YEAR', name='date_precision'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('soldiers', 'posthumous_award_date_precision')
    op.drop_column('soldiers', 'date_of_release_from_captivity_precision')
    op.drop_column('soldiers', 'date_of_burial_precision')
    op.drop_column('soldiers', 'date_of_death_precision')
    op.drop_column('soldiers', 'date_of_disappearance_precision')
    op.drop_column('soldiers', 'date_of_birth_precision')
    # ### end Alembic commands ###
