"""add source url to soldiers

Revision ID: f6213b907f7a
Revises: 3810b76c360f
Create Date: 2026-09-10 10:54:06.464906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6213b907f7a'
down_revision: Union[str, Sequence[str], None] = '3810b76c360f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('soldiers', sa.Column('source_url', sa.String(), nullable=False))
    op.create_index(op.f('ix_soldiers_source_url'), 'soldiers', ['source_url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_soldiers_source_url'), table_name='soldiers')
    op.drop_column('soldiers', 'source_url')
    # ### end Alembic commands ###
